import initAccordion from "./modules/initAccordion.js";
import initAnimacaoScroll from "./modules/initAnimacaoScroll.js";
import initScrollSuave from "./modules/initScrollSuave.js";
import initTabNav from "./modules/initTabNav.js";
import initModal from "./modules/initModal.js";
import initToolTip from "./modules/initToolTip.js";
import initDropdownMenu from "./modules/initDropdownMenu.js";
import initMenuMobile from "./modules/initMenuMobile.js";
import initFuncionamento from "./modules/initFuncionamento.js";
import initFetchAnimais from "./modules/initFetchAnimais.js";

initAccordion();
initAnimacaoScroll();
initScrollSuave();
initTabNav();
initModal();
initToolTip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
